name = "OverflowContexts"
uuid = "649716ba-0eb1-4560-ace2-251185f55281"
authors = ["Nicholas Bauer <nicholasbauer@outlook.com>"]
version = "0.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "1.6"

[extras]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
